apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apex-dispatch-api.fullname" . }}-config
  labels:
    {{- include "apex-dispatch-api.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_DESCRIPTION: {{ .Values.app.description | quote }}
  APP_ENV: {{ .Values.app.environment | quote }}
  APP_VERSION: {{ .Values.app.version | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.app.corsAllowedOrigins | quote }}
  KEYCLOAK_HOST: {{ .Values.keycloak.host | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm | quote }}
