{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "apex-dispatch-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_CLIENT_ID: {{ .Values.secrets.keycloakClientId | quote }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.secrets.keycloakClientSecret | quote }}
  BACKENDS: {{ .Values.secrets.backends | quote }}
{{- end }}
