name: docs

on:
  push:
    branches:
      - docs
      - develop
      - main
    paths:
      - "README.md"
      - "docs/**"
      - "mkdocs.yml"
      - ".github/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs dependencies
        run: pip install mkdocs-material mkdocs-mermaid2-plugin

      - name: Deploy documentation
        run: mkdocs gh-deploy --force
